import { v4 as uuidv4 } from 'uuid';

const puzzles = [
  {
    id: uuidv4(),
    difficulty: 5,
    difficultyName: 'Average',
    imagePath: './images/castLove.png',
    //difficultyId: uuidv4(),
    //puzzleImages_id: uuidv4(),
    solution_id: uuidv4(),
    title: 'Cast Love',
    description: 'Cast Love - description',
    type: 'Assemble and Disassemble puzzle',
    brand: 'Hanayama',
    material: ['Metal'],
    avgScore: 8.5,
    userScore: 'N/A',
    approved: true,
  },
  {
    id: uuidv4(),
    difficulty: 10,
    difficultyName: 'Mind Boggling',
    imagePath: './images/excaliburr.png',
    //difficultyId: uuidv4(),
    //puzzleImages_id: uuidv4(),
    solution_id: uuidv4(),
    title: 'Excaliburr',
    description: 'Excaliburr - description',
    type: 'Remove object from its resting place.',
    brand: 'Pelikan',
    material: ['Wood', 'Metal'],
    avgScore: 6.78,
    userScore: 'N/A',
    approved: true,
  },
  {
    id: uuidv4(),
    difficulty: 7,
    difficultyName: 'Hard',
    imagePath: './images/butterflysRevenge.png',
    //difficultyId: uuidv4(),
    //puzzleImages_id: uuidv4(),
    solution_id: uuidv4(),
    title: "Butterfly's Revenge",
    description: "Butterfly's Revenge - description",
    type: 'Remove the String',
    brand: 'Puzzle Master',
    material: ['String', 'Metal'],
    avgScore: 8.76,
    userScore: 'N/A',
    approved: true,
  },
  {
    id: uuidv4(),
    difficulty: 2,
    difficultyName: 'easy',
    imagePath: './images/mosquito.png',
    //difficultyId: uuidv4(),
    //puzzleImages_id: uuidv4(),
    solution_id: uuidv4(),
    title: 'Mosquito',
    description: 'Mosquito - description',
    type: 'Remove string',
    brand: 'NotApproved',
    material: ['Metal', 'String'],
    avgScore: null,
    userScore: null,
    approved: false,
  },
];

export default puzzles;
